version: '3'

services: 
  web:
    image: "muskanshaikh10/server:latest"
    ports: 
      - "5000:5000"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.1'
          memory: 50m
    restart: on-failure
    networks:
      - webnet
  redis:
    image: "redis:latest"
    deploy:
      replicas: 1
    ports:
      - "6379:6379"
    networks:
      - webnet
networks:
  webnet: