version: "3"
services:
  web:
  #image: dockerhubusername/repo:tag
    image: "muskanshaikh10/web_app:1.0"
deploy:
  replicas: 5
  resources:
    limits:
      cpus: "0.1"
      memory: 50M
      restart: on-failure
      networks:
        - webnet
ports:
  - "4000:80"
networks:
  - webnet
networks:
  webnet:
